from pydantic import BaseModel, EmailStr
from datetime import date
from typing import Optional

# Schema for creating a new member (request body)
class MemberCreate(BaseModel):
    name: str
    email: EmailStr
    phone_number: str
    membership_end: Optional[date] = None  # Can be auto-calculated later

# Schema for returning member data (response model)
class MemberResponse(MemberCreate):
    id: int  # Auto-generated by database

    class Config:
        orm_mode = True  # Allows SQLAlchemy models to be converted to Pydantic
